### PR TITLE
Remove local_time from ActiveTextLogger. Fixes: #2815

### LINKED ISSUE #2815: Remove local_time from ActiveTextLogger
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|   |
---
## Problem Description

`ActiveTextLogger` makes a Posix system call to convert time to a local workstation time.

This code should be removed so it can be run on non-posix platforms:

https://github.com/nasa/fprime/blob/devel/Svc/ActiveTextLogger/ActiveTextLogger.cpp#L84

## Expected Behavior

`ActiveTextLogger` should just print the seconds/subseconds field.

### PR DESCRIPTION
**Pull request by AlesKus**
| | |
|:---|:---|
|**_Related Issue(s)_**|  nasa/fprime#2815 |
|**_Has Unit Tests (y/n)_**| y |
|**_Documentation Included (y/n)_**| y |

---
## Change Description

Removed invocation of the localtime_r.

Fixed unit tests:
* included them into build, after they were removed [#f797734](https://github.com/nasa/fprime/commit/f797734994be47997da3ef597b0f2b09c031ae49#diff-139c7bd2dce517fc4fc50740dac2852ce6e2a072c065b73dfef9b8cd33227173L23) 
* fixed the LogFile behavior, which, I assume, has been broken here: [#58c2141](https://github.com/nasa/fprime/commit/58c21418aac3162156299ad6e0153a1e94288b45#diff-d569e95f05d54e36249f9e06ee4f58631cf460aed9ecfe3c78b0960ce9149ca2R143) ; the intention of `include_excl` flag was to include the O_EXCL option for opening (see [source code](https://nasa.github.io/fprime/v3.1.0/UsersGuide/api/c++/html/os_2_linux_2_file_8cpp_source.html)); therefore `include_excl = false` means `OverwriteType::OVERWRITE`. I've mentioned this behavior in the documentation.

## Rationale

Fixes  nasa/fprime#2815.

## Testing/Review Recommendations

Please review the documentation changes as well.
How to test: run `fprime-util check` in `Svc/ActiveTextLogger`.

## Future Work

1. The component has several TODOs:
* https://github.com/nasa/fprime/blob/devel/Svc/ActiveTextLogger/ActiveTextLogger.cpp#L76
* https://github.com/nasa/fprime/blob/devel/Svc/ActiveTextLogger/test/ut/ActiveTextLoggerTester.cpp#L165
* https://github.com/nasa/fprime/blob/devel/Svc/ActiveTextLogger/docs/sdd.md?plain=1#L30
* https://github.com/nasa/fprime/blob/devel/Svc/ActiveTextLogger/docs/sdd.md?plain=1#L52
Probably, they worth fixing.

2. The test functions might be split to small test cases.

### CODE REVIEW

File: Svc/ActiveTextLogger/test/ut/ActiveTextLoggerTester.cpp [hunk 1]
```diff
@@ -347,6 +346,46 @@ namespace Svc {
...
+      while(logStream) {
+          char buf[256];
+          logStream.getline(buf, 256);
+          if (logStream) {
+              std::cout << "readLine: " << buf << std::endl;
+              char textStr[512];
+              snprintf(textStr, sizeof(textStr),
+                      "EVENT: (%d) (%d:%d,%d) %s: %s",
+                       id,timeTag.getTimeBase(), timeTag.getSeconds(), timeTag.getUSeconds(), severityString, text.toChar());
+              ASSERT_EQ(0, strcmp(textStr, buf));
```
Comment (LeStarch) [inline Svc/ActiveTextLogger/test/ut/ActiveTextLoggerTester.cpp:380]: This can be `ASSERT_STREQ`

File: Svc/ActiveTextLogger/ActiveTextLogger.cpp [hunk 2]
```diff
@@ -76,31 +76,11 @@ namespace Svc {
...
-        else {
-
-            (void) snprintf(textStr,
-                            FW_INTERNAL_INTERFACE_STRING_MAX_SIZE,
-                            "EVENT: (%" PRI_FwEventIdType ") (%" PRI_FwTimeBaseStoreType ":%" PRId32 ",%" PRId32 ") %s: %s\n",
-                            id, static_cast<FwTimeBaseStoreType>(timeTag.getTimeBase()),timeTag.getSeconds(),timeTag.getUSeconds(),severityString,text.toChar());
-        }
+        (void) snprintf(textStr,
+                        FW_INTERNAL_INTERFACE_STRING_MAX_SIZE,
+                        "EVENT: (%" PRI_FwEventIdType ") (%" PRI_FwTimeBaseStoreType ":%" PRId32 ",%" PRId32 ") %s: %s\n",
```
Comment (LeStarch) [inline Svc/ActiveTextLogger/ActiveTextLogger.cpp]: These should say `PRIu32` instead of `PRId32` as these are unsigned values.

**Review by LeStarch — CHANGES_REQUESTED** [review]

**Comment by LeStarch** [comment]
Looks very good!  Only two minor touch-ups.

**Comment by LeStarch** [comment]
I went ahead and made the changes.  Should be good once it passes CI!

**Review by LeStarch — APPROVED** [review]
This file is using multiple styles to compare strings, so let us leave as is.
