### PR TITLE
Add required fixes for F Prime to have deinit triggered by autocode

### LINKED ISSUE #4484: `deinit` Not Called In Tester
| | |
|:---|:---|
|**_F´ Version_**| |
|**_Affected Component_**|   |
---
## Problem Description

F Prime should de-initialize components in the Tester class destructor.  This would ensure that resources clean-up.

This is a fix to unit test implementation templates.

### PR DESCRIPTION
**Pull request by LeStarch**
| | |
|:---|:---|
|**_Related Issue(s)_**|  |
|**_Has Unit Tests (y/n)_**|  |
|**_Documentation Included (y/n)_**|  |
|**_Generative AI was used in this contribution (y/n)_**|  |

---
## Change Description

These changes are needed to pair with the `deinit` in the fpp-to-cpp tool

### CODE REVIEW

File: Fw/Comp/QueuedComponentBase.hpp [hunk 1]
```diff
@@ -26,12 +26,12 @@ class QueuedComponentBase : public PassiveComponentBase {
         MSG_DISPATCH_ERROR,  //!< Errors dispatching messages
         MSG_DISPATCH_EXIT    //!< A message was sent requesting an exit of the loop
     } MsgDispatchStatus;
+    void deinit();  //!< Allows de-initialization on teardown
```
Comment (thomas-bc) [inline Fw/Comp/QueuedComponentBase.hpp:29]: why does `deinit()` need to be public but not `init()` ?

**Review by thomas-bc — APPROVED** [review]
